<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Assert Fail Check]]>
    </line>
    <line>
      <![CDATA[Assert Fail -----> pass]]>
    </line>
  </reporter-output>
  <suite started-at="2023-02-13T15:05:04 IST" name="Default suite" finished-at="2023-02-13T15:05:04 IST" duration-ms="43">
    <groups>
    </groups>
    <test started-at="2023-02-13T15:05:04 IST" name="Default test" finished-at="2023-02-13T15:05:04 IST" duration-ms="43">
      <class name="hardAssert.AssertFail">
        <test-method signature="mainTC()[pri:0, instance:hardAssert.AssertFail@1ddf84b8]" started-at="2023-02-13T15:05:04 IST" name="mainTC" finished-at="2023-02-13T15:05:04 IST" duration-ms="13" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at hardAssert.AssertFail.mainTC(AssertFail.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Assert Fail Check]]>
            </line>
            <line>
              <![CDATA[Assert Fail -----> pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- mainTC -->
      </class> <!-- hardAssert.AssertFail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
